In [0]:
import numpy as np

In [0]:
np.array([[1,2,3,4,5], [4,5,6,7,8]])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [0]:
data = np.array([[[[[[1,2,3,4,5], [4,5,6,7,8]]]]]])

In [0]:
data.ndim

6

In [0]:
data

array([[[[[[1, 2, 3, 4, 5],
           [4, 5, 6, 7, 8]]]]]])

In [0]:
data.shape

(1, 1, 1, 1, 2, 5)

In [0]:
data.dtype

dtype('int64')

In [0]:
type(data)

numpy.ndarray

In [0]:
arr1 = np.zeros(8)

In [0]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
arr3d = arr1.reshape(1,1, 2,2,2)

In [0]:
arr3d

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [0]:
arr3d.ndim

5

In [0]:
arr1 = np.array([1,2,3,4,5, 6])

In [0]:
x =arr1.reshape(1,1,1,2,3)

In [0]:
x

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [0]:
x.ndim

5

In [0]:
y = x.ravel()

In [0]:
y.shape

(6,)

In [0]:
y

array([1, 2, 3, 4, 5, 6])

In [0]:
x.size

6

In [0]:
arr1

array([1, 2, 3, 4, 5, 6])

In [0]:
arr2 = np.array([8,7,6,5,4,7])

In [0]:
arr1-arr2

array([-7, -5, -3, -1,  1, -1])

In [0]:
age =  np.array([18,20,25,26,50,12,1])

In [0]:
eligibility = age>=18

In [0]:
eligibility

array([ True,  True,  True,  True,  True, False, False])

In [0]:
np.sqrt(45)

6.708203932499369

In [0]:
np.log(1000)

6.907755278982137

In [0]:
np.sin(45)

0.8509035245341184

In [0]:
np.tan(45)

1.6197751905438615

In [0]:
np.transpose(np.array([[1,2,3], [4,5,6]]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
np.arange(0,1000,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [0]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [0]:
np.random.randn(1) # z = x-xbar/sd

array([-0.45724385])

In [0]:
np.random.randint(0,10, 100)

array([3, 3, 1, 1, 2, 4, 3, 7, 1, 3, 3, 8, 4, 4, 2, 4, 1, 4, 5, 3, 5, 5,
       5, 7, 8, 1, 9, 7, 0, 3, 2, 1, 6, 1, 6, 3, 2, 5, 7, 0, 4, 3, 8, 2,
       3, 1, 2, 8, 3, 3, 1, 7, 3, 2, 9, 9, 6, 5, 4, 2, 9, 8, 8, 0, 4, 5,
       7, 2, 4, 4, 6, 7, 5, 7, 7, 2, 9, 8, 5, 4, 1, 8, 0, 3, 7, 1, 6, 1,
       4, 0, 7, 5, 2, 6, 4, 9, 5, 1, 9, 6])

In [0]:
# Copy and View()