In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
randn(5,4)

array([[-1.25905185,  0.09189099, -0.04188756,  1.88319653],
       [-1.93364481, -0.46324679,  0.02265931, -0.38073445],
       [ 1.55683923, -0.72871848,  0.1340665 ,  0.26055404],
       [ 0.6314359 , -1.10338725,  0.56274867, -0.85790082],
       [ 0.29660335, -0.38145666,  1.18478517,  1.28821342]])

In [3]:
np.random.seed(101)

In [4]:
df = pd.DataFrame(data =randn(5,4),index = ['A','B','C','D','E'], columns= ['w','x','y','z'])

In [5]:
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
df['zz'] = 0 

In [7]:
df

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826   0
B  0.651118 -0.319318 -0.848077  0.605965   0
C -2.018168  0.740122  0.528813 -0.589001   0
D  0.188695 -0.758872 -0.933237  0.955057   0
E  0.190794  1.978757  2.605967  0.683509   0

In [9]:
df['zz'] = int('nan')

ValueError: invalid literal for int() with base 10: 'nan'

In [10]:
df['zz'] = float('nan')

In [11]:
df

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826 NaN
B  0.651118 -0.319318 -0.848077  0.605965 NaN
C -2.018168  0.740122  0.528813 -0.589001 NaN
D  0.188695 -0.758872 -0.933237  0.955057 NaN
E  0.190794  1.978757  2.605967  0.683509 NaN

In [12]:
df = df.drop(['zz'],axis = 1)

In [13]:
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
df[1:3]

w         x         y         z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [33]:
df.loc['A']    # 

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: A, dtype: float64

In [50]:
df.iloc[0]    # index numer in iloc

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: A, dtype: float64

In [34]:
df.loc['C']

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: C, dtype: float64

In [51]:
df.iloc[2]      # index numer in iloc

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: C, dtype: float64

In [38]:
df.loc[['C']]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001

In [54]:
df.iloc[[2]]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001

In [36]:
df.loc[['B','D']]

w         x         y         z
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [55]:
df.iloc[[1,4]]

w         x         y         z
B  0.651118 -0.319318 -0.848077  0.605965
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df.loc[['B','D','A','C']]

w         x         y         z
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001

In [56]:
df.iloc[[2,4,1,3]]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [39]:
df.loc['D', 'x']

-0.758872056210466

In [63]:
df.iloc[3,1]

-0.758872056210466

In [62]:
df.loc['A':'D', 'x']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
Name: x, dtype: float64

In [60]:
df.iloc[0:4,1]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
Name: x, dtype: float64

In [43]:
df.loc[[False,False,True,False,True]]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [69]:
df.iloc[[False,False,True,False,True]]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [44]:
df.loc[[True,False,False,False,True]]

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [125]:
df.loc[df['x']>1.0]

w         x         y         z
E  0.190794  1.978757  2.605967  0.683509

In [124]:
df.loc[df['x']>1.0,['z']]

z
E  0.683509

In [65]:
df.iloc[[0,4]]

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [70]:
df.loc[[False,False,True,False,True]]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [71]:
df.iloc[[True,False,True,False,True]]

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [72]:
df_dict = {'k1':(1,2,3),'k2':(20,30,40),'k3':(30,40,50),'k4':[100,200,300]}

In [81]:
df_dict

{'k1': (1, 2, 3),
 'k2': (20, 30, 40),
 'k3': (30, 40, 50),
 'k4': [100, 200, 300]}

In [74]:
data_Frame_dict = pd.DataFrame(data = df_dict)
data_Frame_dict

k1  k2  k3   k4
0   1  20  30  100
1   2  30  40  200
2   3  40  50  300

In [75]:
data_Frame_dict = pd.DataFrame(data = df_dict)
print(data_Frame_dict)

   k1  k2  k3   k4
0   1  20  30  100
1   2  30  40  200
2   3  40  50  300


In [76]:
data_Frame_dict = pd.DataFrame(df_dict)
data_Frame_dict

k1  k2  k3   k4
0   1  20  30  100
1   2  30  40  200
2   3  40  50  300

In [77]:
data_series_dict = pd.Series(df_dict)
data_series_dict

k1          (1, 2, 3)
k2       (20, 30, 40)
k3       (30, 40, 50)
k4    [100, 200, 300]
dtype: object

In [78]:
df_ct = {'k1':(1,2,3),'k2':(20,30,40),'k3':(30,40,50),'k4':(100,200,300)}

In [79]:
df_ct

{'k1': (1, 2, 3),
 'k2': (20, 30, 40),
 'k3': (30, 40, 50),
 'k4': (100, 200, 300)}

In [80]:
data_Frame_ct = pd.DataFrame(data = df_ct)
data_Frame_ct

k1  k2  k3   k4
0   1  20  30  100
1   2  30  40  200
2   3  40  50  300

In [82]:
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [83]:
df['x'].values

array([ 0.62813271, -0.31931804,  0.74012206, -0.75887206,  1.97875732])

In [84]:
df['x'].values[2]

0.7401220570561068

In [85]:
df['x'].values[1:3]

array([-0.31931804,  0.74012206])

In [86]:
df[2:4]

w         x         y         z
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [88]:
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [89]:
df.columns

Index(['w', 'x', 'y', 'z'], dtype='object')

In [90]:
df['y'].value_counts()

 0.528813    1
 0.907969    1
-0.848077    1
 2.605967    1
-0.933237    1
Name: y, dtype: int64

In [91]:
df['zz'] = 0

In [92]:
df

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826   0
B  0.651118 -0.319318 -0.848077  0.605965   0
C -2.018168  0.740122  0.528813 -0.589001   0
D  0.188695 -0.758872 -0.933237  0.955057   0
E  0.190794  1.978757  2.605967  0.683509   0

In [94]:
df['zz'] = float('nan')

In [95]:
df

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826 NaN
B  0.651118 -0.319318 -0.848077  0.605965 NaN
C -2.018168  0.740122  0.528813 -0.589001 NaN
D  0.188695 -0.758872 -0.933237  0.955057 NaN
E  0.190794  1.978757  2.605967  0.683509 NaN

In [96]:
df.count()

w     5
x     5
y     5
z     5
zz    0
dtype: int64

In [97]:
df.count().sum()

20

In [98]:
df.isnull()

w      x      y      z    zz
A  False  False  False  False  True
B  False  False  False  False  True
C  False  False  False  False  True
D  False  False  False  False  True
E  False  False  False  False  True

In [99]:
df.isnull().sum()

w     0
x     0
y     0
z     0
zz    5
dtype: int64

In [100]:
df.describe()

w         x         y         z   zz
count  5.000000  5.000000  5.000000  5.000000  0.0
mean   0.343858  0.453764  0.452287  0.431871  NaN
std    1.681131  1.061385  1.454516  0.594708  NaN
min   -2.018168 -0.758872 -0.933237 -0.589001  NaN
25%    0.188695 -0.319318 -0.848077  0.503826  NaN
50%    0.190794  0.628133  0.528813  0.605965  NaN
75%    0.651118  0.740122  0.907969  0.683509  NaN
max    2.706850  1.978757  2.605967  0.955057  NaN

In [102]:
df.describe()['w']

count    5.000000
mean     0.343858
std      1.681131
min     -2.018168
25%      0.188695
50%      0.190794
75%      0.651118
max      2.706850
Name: w, dtype: float64

In [103]:
df['y'].values[1]

-0.8480769834036315

In [105]:
df['z'].values

array([ 0.50382575,  0.60596535, -0.58900053,  0.95505651,  0.68350889])

In [106]:
list(df['z'].values)

[0.5038257538223936,
 0.6059653494949336,
 -0.5890005332865824,
 0.9550565092637361,
 0.6835088855389145]

In [109]:
print (df["y"].mean())
print (df["y"].median())
print (df["y"].mode())
print (df["y"].min())
print (df["y"].max())

0.4522872041305265
0.5288134940893595
0   -0.933237
1   -0.848077
2    0.528813
3    0.907969
4    2.605967
dtype: float64
-0.9332372163009188
2.60596727979128


In [110]:
Sorted = df.sort_values(['x'], ascending=False)
Sorted.head()

w         x         y         z  zz
E  0.190794  1.978757  2.605967  0.683509 NaN
C -2.018168  0.740122  0.528813 -0.589001 NaN
A  2.706850  0.628133  0.907969  0.503826 NaN
B  0.651118 -0.319318 -0.848077  0.605965 NaN
D  0.188695 -0.758872 -0.933237  0.955057 NaN

In [111]:
df[df['x'] < 1.0]

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826 NaN
B  0.651118 -0.319318 -0.848077  0.605965 NaN
C -2.018168  0.740122  0.528813 -0.589001 NaN
D  0.188695 -0.758872 -0.933237  0.955057 NaN

In [112]:
df['x'].min()

-0.758872056210466

In [114]:
df[df['x'] < 1.0].count()

w     4
x     4
y     4
z     4
zz    0
dtype: int64

In [117]:
df[df['x'] > 1.0].count()

w     1
x     1
y     1
z     1
zz    0
dtype: int64

In [118]:
df

w         x         y         z  zz
A  2.706850  0.628133  0.907969  0.503826 NaN
B  0.651118 -0.319318 -0.848077  0.605965 NaN
C -2.018168  0.740122  0.528813 -0.589001 NaN
D  0.188695 -0.758872 -0.933237  0.955057 NaN
E  0.190794  1.978757  2.605967  0.683509 NaN

In [119]:
df = df.drop(['zz'], axis=1)
df.head()

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [120]:
df[(df['x'] <= 0.5) & (df['x'] <= 1.0)]

w         x         y         z
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [121]:
df1 = df[["w"]]
df1.head()

w
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [122]:
df1 = df1.drop_duplicates()
df1

w
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [126]:
df

w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [127]:
df = df>0
print(df)
print(type(df))

       w      x      y      z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True
<class 'pandas.core.frame.DataFrame'>


In [128]:
df

w      x      y      z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True